app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('app1_first/',app1_first,name='app1_first'),
    path('app1_sec/',app1_sec,name='app1_sec'),
]

app2/urls.py
from django.urls import path
from app2.views import *


app_name='app2'

urlpatterns=[
    path('app2_first/',app2_first,name='app2_first'),
    path('app2_sec/',app2_sec,name='app2_sec'),
]

project17/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.def 
def app1_first(request):
    return render(request,'app1_first.html')


def app1_sec(request):
    return render(request,'app1_sec.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_first(request):
    return render(request,'app2_first.html')


def app2_sec(request):
    return render(request,'app2_sec.html')

templates/app1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>app1_first page</h1>
        <a href="{% url 'app1:app1_sec' %}">go to app1_sec</a>
    </center>
</body>
</html>

templates/app1_sec.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            app1_second page
        </h1>
            <a href="{% url 'app1:app1_first' %}">go to app1_first</a>
    </center>
</body>
</html>

templates/app2_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>app2_first page</h1>
        <a href="{% url 'app2:app2_sec' %}">go to app2_sec page</a>
    </center>
</body>
</html>

templates/app2_sec.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>app2_sec page</h1>
    <a href="{% url 'app2:app2_first' %}">go to app2_first page</a>
</center>
</body>
</html>